version: '3.8'

services:
  # Single container that serves both backend and frontend
  n8n-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - NODE_ENV=production
      - JWT_SECRET=your_secret_key_change_in_production
    env_file:
      - .env.docker
    volumes:
      - ./src/database:/app/src/database
      - ./src/uploads:/app/src/uploads
    restart: unless-stopped
