version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - NODE_ENV=production
      - JWT_SECRET=your_secret_key_change_in_production
    env_file:
      - .env.docker
    volumes:
      - ./src/database:/app/src/database
      - ./src/uploads:/app/src/uploads
    restart: unless-stopped

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5005
    depends_on:
      - server
